#   dtst:name of variable in orchestrator:priority in variable form:what to replace
# Namespace

apiVersion: v1
kind: Namespace
metadata:
  name: demos-main #dtst:namespace:10:demos-main
  
---

# Service

apiVersion: v1
kind: Service
metadata:
  name: email-service #dtst:dtsName:1:email-service
  namespace: demos-main #dtst:namespace:10:demos-main
spec:
  selector:
    app: email-service #dtst:dtsName:1:email-service
  ports:
  - name: didcomm
    port: 3001
    targetPort: 3001
    protocol: TCP
  - name: admin
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: q
    port: 2903
    targetPort: 2903
    protocol: TCP
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP

---


# Ingress admin

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: email-service-admin #dtst:dtsName:1:email-service
  namespace: demos-main #dtst:namespace:10:demos-main
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: "198.50.185.225/32"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - a.email-service.demos.dev.2060.io #dtst:dtsName:1:email-service
      secretName: admin.email-service.demos.dev.2060.io-cert #dtst:dtsName:1:email-service
  rules:
    - host: a.email-service.demos.dev.2060.io #dtst:dtsName:1:email-service
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: email-service #dtst:dtsName:1:email-service
                 port:
                   number: 3000

---


# Ingress public

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: email-service-public #dtst:dtsName:1:email-service
  namespace: demos-main #dtst:namespace:10:demos-main
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - email-service.demos.dev.2060.io #dtst:dtsName:1:email-service
      secretName: public.email-service.demos.dev.2060.io-cert #dtst:dtsName:1:email-service
  rules:
    - host: email-service.demos.dev.2060.io #dtst:dtsName:1:email-service
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: email-service #dtst:dtsName:1:email-service
                 port:
                   number: 3001

---

# Ingress ds

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: email-service-ds #dtst:dtsName:1:email-service
  namespace: demos-main #dtst:namespace:10:demos-main
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: "51.79.89.27/32"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - q.email-service.demos.dev.2060.io #dtst:dtsName:1:email-service
      secretName: ds-email-service.demos.dev.2060.io-cert #dtst:dtsName:1:email-service
  rules:
    - host: q.email-service.demos.dev.2060.io #dtst:dtsName:1:email-service
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: email-service #dtst:dtsName:1:email-service
                 port:
                   number: 2903


---


apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: email-service #dtst:dtsName:1:email-service
   namespace: demos-main #dtst:namespace:10:demos-main
   labels:
      app: nginx
spec:
   serviceName: "email-service" #dtst:dtsName::email-service
   replicas: 1 #dtst:replicas:0:1
   selector:
      matchLabels:
         app: email-service #dtst:dtsName::email-service
   template:
      metadata:
         labels:
            app: email-service #dtst:dtsName::email-service
      spec:
         containers:
         -  name: email-service-sa-container #dtst:dtsName::email-service
            image: io2060/2060-service-agent:main
            imagePullPolicy: Always
            env:
            - name: AGENT_ENDPOINT
              value: "wss://email-service.demos.dev.2060.io:443" #dtst:dtsName:1:email-service
            - name: AGENT_NAME
              value: "Modern Bank" #dtst:agentName:2:Modern Bank
            - name: AGENT_INVITATION_IMAGE_URL
              value: "https://i.email-service.demos.dev.2060.io/avatar.png" #dtst:dtsName:1:email-service
            - name: EVENTS_BASE_URL
              value: "http://localhost:2903"
            - name: AGENT_PUBLIC_DID
              value: "did:web:email-service.demos.dev.2060.io" #dtst:dtsName:1:email-service
            - name: ANONCREDS_SERVICE_BASE_URL
              value: "https://email-service.demos.dev.2060.io" #dtst:dtsName:1:email-service
              
            volumeMounts:
            - name: email-service-sa-pv-main #dtst:dtsName:1:email-service
              mountPath: /root/.afj
            ports:
            -  containerPort: 3000
            -  containerPort: 3001
         -  name: email-service-backend-container #dtst:dtsName:1:email-service
            image: io2060/2060-demos-email-verification-service:main
            imagePullPolicy: Always
            env:
            - name: SERVICE_AGENT_ADMIN_BASE_URL
              value: "http://localhost:3000"
            - name: PUBLIC_BASE_URL
              value: "https://email-service.demos.dev.2060.io" #dtst:dtsName:1:email-service
            - name: PNVS_SERVICE_AGENT_ADMIN_BASE_URL
              value: "https://a.email-service.demos.dev.2060.io" #dtst:dtsName:1:email-service
            - name: DEBUG
              value: "1"
            - name: QUARKUS_HTTP_PORT
              value: "2903"
            - name: IO_TWENTYSIXTY_SA_RES_C_MESSAGERESOURCE_MP_REST_URL
              value: "http://localhost:3000"
            - name: IO_TWENTYSIXTY_SA_RES_C_CREDENTIALTYPERESOURCE_MP_REST_URL
              value: "http://localhost:3000"
            - name: QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE
              value: "1"
            - name: IO_TWENTYSIXTY_EMAILVS_SENDMAIL_FROM
              value: "root@gmail.com"
            - name: IO_TWENTYSIXTY_EMAILVS_SENDMAIL_SMTP_HOSTNAME
              value: "smtp.gmail.com"
            - name: IO_TWENTYSIXTY_EMAILVS_SENDMAIL_SMTP_PORT
              value: "587"
            - name: IO_TWENTYSIXTY_EMAILVS_SENDMAIL_SMTP_USERNAME
              value: "root@gmail.com"
            - name: IO_TWENTYSIXTY_EMAILVS_SENDMAIL_SMTP_PASSWORD
              value: "password" #dtst:emailPWD:1:password
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "emailvs" 
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "password" #dtst:dbPWD:1:password
            ports:
            -  containerPort: 2903
         -  name: postgres
            image: postgres:15.2
            imagePullPolicy: Always
            env:
            - name: POSTGRES_PASSWORD
              value: "password" #dtst:dbPWD:1:password
            - name: POSTGRES_USER
              value: "emailvs"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            ports:
            -  containerPort: 5432
            volumeMounts:
            - name: email-service-pg-pv-main #dtst:dtsName::email-service
              mountPath: /var/lib/postgresql/data
   volumeClaimTemplates:
   - metadata:
       name: email-service-sa-pv-main #dtst:dtsName::email-service
     spec:
       storageClassName: csi-cinder-classic
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 1Gi
   - metadata:
       name: email-service-pg-pv-main #dtst:dtsName::email-service
     spec:
       storageClassName: csi-cinder-classic
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 1Gi
