# Namespace

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  
---

# Service

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dtsName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.dtsName }}
  ports:
  - name: didcomm
    port: 3001
    targetPort: 3001
    protocol: TCP
  - name: admin
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: q
    port: 2903
    targetPort: 2903
    protocol: TCP
  - name: ds
    port: 2904
    targetPort: 2904
    protocol: TCP
  - name: artemis1
    port: 8161
    targetPort: 8161
    protocol: TCP
  - name: artemis2
    port: 61616
    targetPort: 61616
    protocol: TCP
  - name: artemis3
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: nginx
    port: 80
    targetPort: 80
    protocol: TCP
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP


---


# Ingress admin

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.dtsName }}-admin
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: "198.50.185.225/32"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - a.{{ .Values.dtsName }}.demos.dev.2060.io
      secretName: admin.{{ .Values.dtsName }}.demos.dev.2060.io-cert
  rules:
    - host: a.{{ .Values.dtsName }}.demos.dev.2060.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: {{ .Values.dtsName }}
                 port:
                   number: 3000

---


# Ingress public

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.dtsName }}-public
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.dtsName }}.demos.dev.2060.io
        - i.{{ .Values.dtsName }}.demos.dev.2060.io
      secretName: public.{{ .Values.dtsName }}.demos.dev.2060.io-cert
  rules:
    - host: {{ .Values.dtsName }}.demos.dev.2060.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: {{ .Values.dtsName }}
                 port:
                   number: 3001
    - host: i.{{ .Values.dtsName }}.demos.dev.2060.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: {{ .Values.dtsName }}
                 port:
                   number: 80

---

# Ingress ds

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.dtsName }}-ds
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: "51.79.89.27/32"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - q.{{ .Values.dtsName }}.demos.dev.2060.io
        - d.{{ .Values.dtsName }}.demos.dev.2060.io
      secretName: ds-{{ .Values.dtsName }}.demos.dev.2060.io-cert
  rules:
    - host: q.{{ .Values.dtsName }}.demos.dev.2060.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: {{ .Values.dtsName }}
                 port:
                   number: 2903
    - host: d.{{ .Values.dtsName }}.demos.dev.2060.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: {{ .Values.dtsName }}
                 port:
                   number: 2904


---


apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: {{ .Values.dtsName }}
   namespace: {{ .Values.namespace }}
   labels:
      app: nginx
spec:
   serviceName: "{{ .Values.dtsName }}"
   replicas: {{ .Values.replicas }}
   selector:
      matchLabels:
         app: {{ .Values.dtsName }}
   template:
      metadata:
         labels:
            app: {{ .Values.dtsName }}
      spec:
         initContainers:
         - name: volume-gid-ds
           image: busybox
           command: ["sh", "-c", "chown -R 185:0 /home/data"]
           volumeMounts:
           - name: {{ .Values.dtsName }}-data-store-main
             mountPath: /home/data
         containers:
         -  name: {{ .Values.dtsName }}-sa-container
            image: io2060/2060-service-agent:dev
            imagePullPolicy: Always
            env:
            - name: AGENT_ENDPOINT
              value: "wss://{{ .Values.dtsName }}.demos.dev.2060.io:443"
            - name: AGENT_LABEL
              value: {{ .Values.agentName }}
            - name: AGENT_INVITATION_IMAGE_URL
              value: "https://i.{{ .Values.dtsName }}.demos.dev.2060.io/avatar.png"
            - name: EVENTS_BASE_URL
              value: "http://localhost:2903"
            - name: AGENT_PUBLIC_DID
              value: "did:web:{{ .Values.dtsName }}.demos.dev.2060.io"
            - name: ANONCREDS_SERVICE_BASE_URL
              value: "https://{{ .Values.dtsName }}.demos.dev.2060.io"
            volumeMounts:
            - name: {{ .Values.dtsName }}-sa-pv-main
              mountPath: /root/.afj
            ports:
            -  containerPort: 3000
            -  containerPort: 3001
         -  name: {{ .Values.dtsName }}-backend-container
            image: io2060/fastbot-conversational-dts:dev
            imagePullPolicy: Always
            env:
            - name: SERVICE_AGENT_ADMIN_BASE_URL
              value: "http://localhost:3000"
            - name: PUBLIC_BASE_URL
              value: "https://{{ .Values.dtsName }}.demos.dev.2060.io"
            - name: PNVS_SERVICE_AGENT_ADMIN_BASE_URL
              value: "https://a.{{ .Values.dtsName }}.demos.dev.2060.io"
            - name: DEBUG
              value: "1"
            - name: QUARKUS_HTTP_PORT
              value: "2903"
            - name: IO_TWENTYSIXTY_SA_RES_C_V1_MESSAGERESOURCE_MP_REST_URL
              value: "http://localhost:3000"
            - name: IO_TWENTYSIXTY_SA_RES_C_V1_CREDENTIALTYPERESOURCE_MP_REST_URL
              value: "http://localhost:3000"
            - name: COM_MOBIERA_CHATAPP_FASTBOT_RES_C_MEDIARESOURCE_MP_REST_URL
              value: "http://localhost:2904"
            - name: COM_MOBIERA_CHATAPP_FASTBOT_RES_C_MEDIARESOURCE_MP_REST_ENABLED
              value: {{ .Values.dtsMediaSt }}
            - name: QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE
              value: "1"
            - name: COM_MOBIERA_CHATAPP_FASTBOT_LANGUAGE
              value: {{ .Values.language }}
            - name: COM_MOBIERA_CHATAPP_FASTBOT_JMS_QUEUE_ID
              value: {{ .Values.queue }}
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://localhost/easychat
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "easychat" 
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: {{ .Values.dbPWD }}
            - name: QUARKUS_ARTEMIS_USERNAME
              value: "quarkus" 
            - name: QUARKUS_ARTEMIS_PASSWORD
              value: {{ .Values.quarkusPWD }}
            - name: IO_TWENTYSIXTY_DTS_ENTITY_ID
              value: {{ .Values.dtsId }}
            - name: QUARKUS_ARTEMIS_URL
              value: "tcp://artemis-broker-hdls-svc.activemq-artemis-operator:61616"
            - name: IO_TWENTYSIXTY_ORCHESTRATOR_RES_C_REGISTERRESOURCE_MP_REST_URL
              value: {{ .Values.orchestratorUrl }}
            - name: IO_TWENTYSIXTY_ORCHESTRATOR_RES_C_PARAMETERRESOURCE_MP_REST_URL
              value: {{ .Values.orchestratorUrl }}
            - name: IO_TWENTYSIXTY_ORCHESTRATOR_RES_C_DTSRESOURCE_MP_REST_URL
              value: {{ .Values.orchestratorUrl }}
            - name: IO_TWENTYSIXTY_ORCHESTRATOR_RES_C_CAMPAIGNRESOURCE_MP_REST_URL
              value: {{ .Values.orchestratorUrl }}
            - name: IO_TWENTYSIXTY_ORCHESTRATOR_RES_C_CAMPAIGNSCHEDULERESOURCE_MP_REST_URL
              value: {{ .Values.orchestratorUrl }}
            ports:
            -  containerPort: 2903
         -  name: {{ .Values.dtsName }}-data-store-container
            image: io2060/2060-datastore:main
            imagePullPolicy: Always
            env:
            - name: DEBUG
              value: "1"
            - name: QUARKUS_HTTP_PORT
              value: "2904"
            - name: IO_TWENTYSIXTY_DATASTORE_TMP_DIR
              value: "/home/data/tmp"
            - name: IO_TWENTYSIXTY_DATASTORE_TMP_LIFETIMEDAYS
              value: "5"
            - name: IO_TWENTYSIXTY_DATASTORE_REPO_LIFETIMEDAYS
              value: "43800"
            - name: IO_TWENTYSIXTY_DATASTORE_REPO_FS_DIR
              value: "/home/data/repo"
            - name: IO_TWENTYSIXTY_DATASTORE_MEDIA_MAXCHUNKS
              value: "128"
            ports:
            -  containerPort: 2904
            volumeMounts:
            - name: {{ .Values.dtsName }}-data-store-main
              mountPath: /home/data
         -  name: postgres
            image: postgres:15.2
            imagePullPolicy: Always
            env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.dbPWD }}
            - name: POSTGRES_USER
              value: "easychat"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            ports:
            -  containerPort: 5432
            volumeMounts:
            - name: {{ .Values.dtsName }}-pg-pv-main
              mountPath: /var/lib/postgresql/data
   volumeClaimTemplates:
   - metadata:
       name: {{ .Values.dtsName }}-sa-pv-main
     spec:
       storageClassName: csi-cinder-classic
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 1Gi
   - metadata:
       name: {{ .Values.dtsName }}-pg-pv-main
     spec:
       storageClassName: csi-cinder-classic
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 1Gi
   - metadata:
       name: {{ .Values.dtsName }}-data-store-main
     spec:
       storageClassName: csi-cinder-classic
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 1Gi
